apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-private-https
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: myweb
              port: 
                number: 80
      host: web2.private.demo
  tls:
    - hosts:
      - web2.private.demo
      secretName: web2-cert