  
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-monitor-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: appgw
spec:
  scaleTargetRef:
    name: kedaweb
  pollingInterval: 5
  cooldownPeriod:  15
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-monitor
    metadata:
      resourceURI: Microsoft.Network/applicationGateways/appgw
      tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscriptionId: a0f4a733-4fce-4d49-b8a8-d30541fc1b45
      resourceGroupName: MC_aks-imperative-rg_aks_westeurope
      metricName: AvgRequestCountPerHealthyHost
      metricFilter: BackendSettingsPool eq 'pool-default-myweb-80-bp-80~bp-default-myweb-80-80-ingress-agic-kedaweb' 
      metricAggregationInterval: "0:1:0"
      metricAggregationType: Average
      targetValue: "230"
    authenticationRef:
        name: azure-monitor-auth