kind: Service
apiVersion: v1
metadata:
  name: myweb-service-ext-private-static
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "intlb-subnet"
spec:
  loadBalancerIP: 10.0.1.100
  selector:
    app: myweb
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80