apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: tomaskubica8.azurecr.io/web:v1
        env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8080"
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: myimages
            mountPath: /opt/bitnami/nginx/html/images
          - name: config-volume
            mountPath: /opt/bitnami/nginx/conf/vhosts/
      volumes:
        - name: myimages
          azureFile:
            secretName: images-secret
            shareName: images
            readOnly: true
        - name: config-volume
          configMap:
            name: healthvhostconf