apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: basic-demo
spec:
  chart:
    git: https://github.com/tkubica12/aks-demo
    ref: master
    path: helm/basic-demo
  values:
    subscriptionId: a0f4a733-4fce-4d49-b8a8-d30541fc1b45
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    rg: aks-demo
    dnsZone: private.demo
    keyvaultName: kv-5jl6tmwrp3lkm