apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    repository: https://charts.jetstack.io
      name: cert-manager
      version: v1.2.0
    values:
      installCRDs: true