apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dapr-system
spec:
  chart:
    repository: https://dapr.github.io/helm-charts
    name: dapr
    version: 1.1.1
  values:
    installCRDs: true