apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dapr-demo
spec:
  targetNamespace: dapr
  chart:
    git: https://github.com/tkubica12/aks-demo
    ref: master
    path: helm/dapr-demo
  dependsOn:
    - name: dapr-system
  valuesFrom:
  - secretKeyRef:
      name: configurations
      namespace: default
      key: values.yaml
      optional: true
  values:
    providerimage: tkubica/twitter-provider:1
    processorimage: tkubica/twitter-processor:1
    viewerimage: tkubica/twitter-viewer:1
    query: Microsoft
