apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keda-system
spec:
  targetNamespace: keda
  chart:
    repository: https://kedacore.github.io/charts
    name: kedacore
    version: v2.2.1
  values:
    podIdentity:
      activeDirectory:
        identity: keda
