apiVersion: v1
kind: Namespace
metadata:
  name: dapr
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
---
apiVersion: v1
kind: Namespace
metadata:
  name: openservicemesh
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginxingress
