apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: policies-demo
spec:
  targetNamespace: secure
  chart:
    git: https://github.com/tkubica12/aks-demo
    ref: master
    path: helm/policies-demo
  valuesFrom:
  - secretKeyRef:
      name: configurations
      namespace: secure
      key: values.yaml
      optional: true