apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-affinity
spec:
  selector:
    matchLabels:
      app: missing-affinity
  template:
    metadata:
      labels:
        app: missing-affinity
    spec:
      containers:
      - name: container
        image: {{ .Values.acrName }}.azurecr.io/alpine:latest
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
        args:
          - "tail"
          - "-f"
          - "/dev/null"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000