apiVersion: apps/v1
kind: Deployment
metadata:
  name: nolimits
spec:
  selector:
    matchLabels:
      app: nolimits
  template:
    metadata:
      labels:
        app: nolimits
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values: ["protected"]
      containers:
      - name: container
        image: {{ .Values.acrName }}.azurecr.io/alpine:latest
        args:
          - "tail"
          - "-f"
          - "/dev/null"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000