apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        aadpodidbinding: secrets-reader
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tweet-processor"
        dapr.io/app-port: "3002"
        dapr.io/log-as-json: "true"
        dapr.io/app-protocol: grpc
        # dapr.io/config: "tracing"
    spec:
      containers:
      - name: processor
        image: {{ .Values.processorimage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: APP_PORT
          value: "3002"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: SECRET_STORE_NAME
          value: azurekeyvault
        - name: SECRET_STORE_ENDPOINT
          value: cs-endpoint
        - name: SECRET_STORE_KEY
          value: cs-key