apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-agic-public-dapr
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  rules:
    - http:
        paths:
        - path: /viewer
          backend:
            serviceName: viewer
            servicePort: 80
      host: {{ .Values.appGwDns }}