apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue
  labels: {}
spec:
  scaleTargetRef:
    name: keda-worker
  pollingInterval: 5
  cooldownPeriod:  15
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: azure-queue
    metadata:
      direction: in
      queueName: myqueue
      connectionFromEnv: AzureWebJobsStorage
      accountName: {{ .Values.storageName }}
    authenticationRef:
      name: azure-monitor-auth