apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: keda-secrets-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                              
    useVMManagedIdentity: "false"                                         
    keyvaultName: {{ .Values.keyvaultName }}                         
    objects: |
      array:
        - |
          objectName: storage     
          objectType: secret         
          objectVersion: "" 
    tenantId: {{ .Values.tenantId }}
  secretObjects:                             
    - secretName: dapr-secrets 
      type: Opaque 
      data:
        - key: storage    
          objectName: storage 