kind: HTTPRouteGroup
apiVersion: specs.smi-spec.io/v1alpha4
metadata:
  name: routes1
spec:
  matches:
  - name: all-gets
    pathRegex: ".*"
    methods:
      - GET
---
kind: TCPRoute
apiVersion: specs.smi-spec.io/v1alpha4
metadata:
  name: tcp-ports
spec:
  matches:
    ports:
    - 80
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: access-app1-to-app2
spec:
  destination:
    kind: ServiceAccount
    name: app2
  rules:
#   - kind: HTTPRouteGroup
#     name: routes1
#     matches:
#     - all-gets
  - kind: TCPRoute
    name: tcp-ports
  sources:
  - kind: ServiceAccount
    name: app1