kind: Service
apiVersion: v1
metadata:
  name: app2
spec:
  selector:
    app: app2
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app2-ab
spec:
  selector:
    app: app2
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80