apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      serviceAccountName: app3
      containers:
      - name: myweb
        image: tkubica/web:python-1
        env:
        - name: PORT
          value: "80"
        - name: INFO
          value: "app3"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 500m
            memory: 256M
---
kind: Service
apiVersion: v1
metadata:
  name: app3
spec:
  selector:
    app: app3
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app3