apiVersion: "v1"
kind: "Secret"
metadata:
  name: azure-config-file
type: "Opaque"
stringData:
  azure.json: |-
    {
        "tenantId": "{{ .Values.tenantId }}",
        "subscriptionId": "{{ .Values.subscriptionId }}",
        "resourceGroup": "{{ .Values.rg }}",
        "useManagedIdentityExtension": true
    }