apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                              
    useVMManagedIdentity: "false"                                         
    keyvaultName: tomaskeyvault45                         
    objects: |
      array:
        - |
          objectName: mysecret     
          objectType: secret         
          objectVersion: "" 
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"