apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                              
    useVMManagedIdentity: "false"                                         
    keyvaultName: {{ .Values.keyvaultName }}                         
    objects: |
      array:
        - |
          objectName: mysecret     
          objectType: secret         
          objectVersion: "" 
        - |
          objectName: appinsights     
          objectType: secret        
          objectVersion: "" 
        - |
          objectName: appinsights-string     
          objectType: secret        
          objectVersion: "" 
    tenantId: {{ .Values.tenantId }}